=== djibzo/PROJET-EXAMEN-XML/xml_and_dtd/participations.dtd
<!ELEMENT participations (participation*)>
<!ELEMENT participation (id, user_id, event_id, date_inscription, statut)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT user_id (#PCDATA)>
<!ELEMENT event_id (#PCDATA)>
<!ELEMENT date_inscription (#PCDATA)>
<!ELEMENT statut (#PCDATA)>

=== djibzo/PROJET-EXAMEN-XML/xml/participations.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE participations SYSTEM "participations.dtd">
<participations>
  <participation>
    <id>1</id>
    <user_id>1</user_id>
    <event_id>1</event_id>
    <date_inscription>2025-07-25</date_inscription>
    <statut>confirmé</statut>
  </participation>
  <participation>
    <id>2</id>
    <user_id>1</user_id>
    <event_id>2</event_id>
    <date_inscription>2025-07-24</date_inscription>
    <statut>en_attente</statut>
  </participation>
  <participation>
    <id>3</id>
    <user_id>2</user_id>
    <event_id>1</event_id>
    <date_inscription>2025-07-23</date_inscription>
    <statut>confirmé</statut>
  </participation>
</participations>
