=== djibzo/PROJET-EXAMEN-XML/xml/evenements.dtd
<!ELEMENT evenements (evenement*)>
<!ELEMENT evenement (id, titre, date, lieu)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT lieu (#PCDATA)>

=== djibzo/PROJET-EXAMEN-XML/xml/evenements.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE evenements SYSTEM "evenements.dtd">
<evenements>
  <evenement>
    <id>1</id>
    <titre>Conf√©rence sur l'IA</titre>
    <date>2025-07-30</date>
    <lieu>Dakar</lieu>
  </evenement>
  <evenement>
    <id>2</id>
    <titre>Atelier de programmation</titre>
    <date>2025-08-15</date>
    <lieu>Paris</lieu>
  </evenement>
</evenements>
